// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const ON_SUCCESS = 'ON_SUCCESS';
export const SOMETHING_PENDING = 'SOMETHING_PENDING';
export const SOMETHING_FULFILLED = 'SOMETHING_FULFILLED';
export const CLEAR_SOMETHING_FULFILLED = 'CLEAR_SOMETHING_FULFILLED';
export const CLEAR_SOMETHING_PENDING = 'CLEAR_SOMETHING_PENDING';

//STORE
export const SET_STORE_DETAIL = 'SET_STORE_DETAIL';
export const SET_PAYMENT_DETAIL = 'SET_PAYMENT_DETAIL';
export const SET_ACTIVATED = 'SET_ACTIVATED';
export const GET_PAYMENT_DETAIL = 'GET_PAYMENT_DETAIL';
export const GET_STORE_DETAIL = 'GET_STORE_DETAIL';
export const SET_STORE_CHECK = 'SET_STORE_CHECK';

export const UPDATE_PAYMENT_DETAIL = 'UPDATE_PAYMENT_DETAIL';
export const DELETE_PAYMENT_DETAIL = 'DELETE_PAYMENT_DETAIL';

// EMPLOYEE
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const LOADING_EMPLOYEE = 'LOADING_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const SET_PATH = 'SET_PATH';
export const GET_ALLEMPLOYEE = 'GET_ALLEMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';

//MENU
export const ADD_MENU_ITEM = 'ADD_MENU_ITEM';
export const DELETE_MENU_ITEM = 'DELETE_MENU_ITEM';
export const ADD_MENU_TYPE = 'ADD_MENU_TYPE';
export const DELETE_MENU_TYPE = 'DELETE_MENU_TYPE';
export const GET_ALL_MENU = 'GET_ALL_MENU';
export const UPDATE_MENU_ITEM = 'UPDATE_MENU_ITEM';
export const UPDATE_MENU_TYPE = 'UPDATE_MENU_TYPE';

//Order
export const ADD_ORDER_ITEM = 'ADD_ORDER_ITEM';
export const DELETE_ORDER_ITEM = 'DELETE_ORDER_ITEM';
export const DELETE_MENU_IN_ORDER = 'DELETE_MENU_IN_ORDER';
export const UPDATE_ORDER_ITEM = 'UPDATE_ORDER_ITEM';
export const GET_ALL_ORDER_ITEM = 'GET_ALL_ORDER_ITEM';
export const ORDER_CHANGE = 'ORDER_CHANGE';
export const ORDER_MENU_CHANGE = 'ORDER_MENU_CHANGE';
export const EDIT_ORDER_ITEM = 'EDIT_ORDER_ITEM';
export const CHANGE_BILL_LIST = 'CHANGE_BILL_LIST';
export const SPLIT_ORDER_ITEM = 'SPLIT_ORDER_ITEM';

//KITCHEN
export const KITCHEN_ADD_CARD = 'KITCHEN_ADD_CARD';
export const KITCHEN_DELETE_CARD = 'KITCHEN_DELETE_CARD';
export const KITCHEN_DRAG_HAPPENDED = 'KITCHEN_DRAG_HAPPENDED';
export const KITCHEN_SET_ALL_ORDER = 'KITCHEN_SET_ALL_ORDER';
export const KITCHEN_CHANGE = 'KITCHEN_CHANGE';

//COUPONNNNNNNN
export const COUPON_GET_ALL = 'COUPON_GET_ALL';
export const COUPON_ADD = 'COUPON_ADD';
export const COUPON_DELETE = 'COUPON_DELETE';
//export const COUPON_UPDATE = 'COUPON_UPDATE'

export const SET_LINK = 'SET_LINK';

//LOGGGGGGGGGGGGGGGGGGGG
export const SET_LOG = 'SET_LOG';
export const ADD_LOG = 'ADD_LOG';
export const LOG_CHANGE = 'LOG_CHANGE';
export const REFUND_LOG = 'REFUND_LOG';
